# Install and import sklearn

In [1]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
import pandas as pd
from sklearn import datasets,model_selection,preprocessing,metrics

# Load Data

In [3]:
df=pd.read_csv("sample_sklearn_dataset.csv")
from sklearn.datasets import load_iris
iris=load_iris()
x=iris.data
y=iris.target

In [4]:
df=pd.DataFrame(iris.data,columns=iris.feature_names)
df["target"]=iris.target

# Split into train/Test 

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

# Preprocessing Tools

In [6]:
# scaling
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

# Choose and train a Model

In [7]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

# Prediction

In [8]:
y_pred = model.predict(x_test)

# Evaluate Model

In [10]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print("Accuracy: ",accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Accuracy:  1.0
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

