In [2]:
import numpy as np


## create array from list

In [17]:
arr_1d = np.array([1,2,3,4,5,6])
print(arr_1d)
arr_2d= np.array([[1,2,3],[5,6,7],[11,22,33]])
print(arr_2d)

[1 2 3 4 5 6]
[[ 1  2  3]
 [ 5  6  7]
 [11 22 33]]


In [18]:
py_list=[1,2,3]
print(py_list *2)


[1, 2, 3, 1, 2, 3]


In [21]:
array_mul=np.arange(5)
array_mul*2  #Element wise multiplication

array([0, 2, 4, 6, 8])

In [23]:
import time
start=time.time()
py_list=[i*2 for i in range(100000)]
print("List operation time: ",time.time()-start)
start=time.time()
np_array=np.arange(1000000)*2
print("Numpy operation time: ",time.time()-start)

List operation time:  0.02246379852294922
Numpy operation time:  0.007470846176147461


In [32]:
zeros=np.zeros((2,2))
print("Array of zeroes: \n", zeros)

Array of zeroes: 
 [[0. 0.]
 [0. 0.]]


In [33]:
ones=np.ones((2,2))
print("Array of ones: \n",ones)

Array of ones: 
 [[1. 1.]
 [1. 1.]]


In [35]:
full=np.full((2,2),7)
print("Array of any const: \n",full)

Array of any const: 
 [[7 7]
 [7 7]]


In [6]:
random=np.random.random((2,2))
random

array([[0.90057988, 0.46162654],
       [0.1968186 , 0.63349155]])

In [8]:
sequence= np.arange(0,10,2)
sequence

array([0, 2, 4, 6, 8])

__Vector,Matrix and Tensor__

In [ ]:
vector=[1,2,3,4,5]
print("vector:\n ",vector)
matrix=np.array([[1,2],[33,45]])
print("matrix: \n",matrix)
tensor= np.array([[[1,2],[3,4]],[[11,22],[67,89]]])
print("tensor: \n",tensor)

In [13]:
print(np.array(5))

5


__Array Properties__

In [17]:
arr=np.array([[1,2],[3,4]])
print("Shape: ",arr.shape)
print("Size: ",arr.size)
print("Dimension: ",arr.ndim)
print("Dtype: ",arr.dtype)

Shape:  (2, 2)
Size:  4
Dimension:  2
Dtype:  int32


__Array reshaping__

In [29]:
original=np.arange(12)
print("original array: ",original)
reshape=original.reshape(3,4)
print("Reshape array: ",reshape)
flatten=reshape.flatten()
print("flatten array: ",flatten)

original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshape array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flatten array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [28]:
#ravel (return views ,instead of copy)
revealed=reshape.ravel()
print("ravel array: ",revealed)

ravel array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]


__Transpose__

In [33]:
print(reshape)
transpose=reshape.transpose()
print("Transpose:\n ",transpose)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Transpose:
  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


__Array operation__

In [38]:
arr_1d=np.arange(10)
print(arr_1d)
print(arr_1d[3:11:2])
print(arr_1d[::-1])

[0 1 2 3 4 5 6 7 8 9]
[3 5 7 9]
[9 8 7 6 5 4 3 2 1 0]


In [39]:
arr_2d=np.array([[1,2,3],[44,56,78],[21,34,66]])
print(arr_2d)

[[ 1  2  3]
 [44 56 78]
 [21 34 66]]


In [42]:
print("specific element",arr_2d[0,1])
print("Entire row",arr_2d[2])
print("Entire column",arr_2d[:,1])

specific element 2
Entire row [21 34 66]
Entire column [ 2 56 34]


__sorting__

In [45]:
unsorted=np.array([11,92,31,4,95,6,9])
print("sorted array: ",np.sort(unsorted))

sorted array:  [ 4  6  9 11 31 92 95]


In [50]:
arr_2d_unsorted = np.array([[111,2],[23,56],[78,43]])
print(arr_2d_unsorted)
print("sorted 2D array: \n",np.sort(arr_2d_unsorted, axis=1))

[[111   2]
 [ 23  56]
 [ 78  43]]
sorted 2D array: 
 [[  2 111]
 [ 23  56]
 [ 43  78]]


__Filter__

In [53]:
numbers=np.arange(1,11)
print(numbers)
even_num=numbers[numbers %2==0]
print(even_num)

[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10]


__Filter with mask__

In [56]:
sk=numbers>5
print("Numbers greater than 5: ",numbers[sk])

Numbers greater than 5:  [ 6  7  8  9 10]


__Fancy indexing vs np.where()__

In [58]:
indices=[0,1,2]
print(numbers[indices])
where_result=np.where(numbers>5)
print("NP where",numbers[where_result])

[1 2 3]
NP where [ 6  7  8  9 10]


In [64]:
condition_array=np.where(numbers>5,numbers*2,numbers)
print(condition_array)
#just like if else stm

[ 1  2  3  4  5 12 14 16 18 20]


__Addition and removal of array__

In [6]:
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,1,10])
combine=arr1+arr2
print(combine)
concatenate=np.concatenate([arr1,arr2])
print(concatenate)

[ 7  9 11  5 15]
[ 1  2  3  4  5  6  7  8  1 10]


In [8]:
a=np.array([1,2])
b=np.array([9,12,99])
print(a.shape == b.shape)

False


In [17]:
original=np.array([[1,2],[3,4]])
new_row=np.array([[44,21]])
with_new_row=np.vstack((original,new_row))
print("row add \n",with_new_row)
new_col=np.array([[5],[8]])
with_new_col=np.hstack((original,new_col))
print("column add \n",with_new_col)

row add 
 [[ 1  2]
 [ 3  4]
 [44 21]]
column add 
 [[1 2 5]
 [3 4 8]]


In [20]:
a=np.array([1,2,3,4])
delete=np.delete(a,2)
print("Array after deletion: ",delete)
b=np.array([[1,2],[34,78]])
delete_2d_array=np.delete(b,[0,0])
print("2d_Array after deletion: ",delete_2d_array) 

Array after deletion:  [1 2 4]
2d_Array after deletion:  [ 2 34 78]
